#!/usr/bin/env bash

# This file is part of util-linux.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Copyright (C) 2025 Christian Goeschel Ndjomouo <cgoesc2@wgu.edu>

TS_TOPDIR="${0%/*}/../.."
TS_DESC="getino"

. "$TS_TOPDIR/functions.sh"
ts_init "$*"
ts_skip_nonroot

ts_check_test_command "$TS_CMD_GETINO"
ts_check_test_command "$TS_CMD_UNSHARE"
ts_check_test_command "$TS_CMD_RUNUSER"
ts_check_test_command "$TS_HELPER_STRERROR"
ts_check_prog "stat"

# make sure we do not use shell built-in command
if [ "$TS_USE_SYSTEM_COMMANDS" == "yes" ]; then
	TS_CMD_KILL="$(which kill)"
fi

# The pidfs was only introduced in kernel version 6.9,
# which means we cannot get a valid pidfd from earlier versions,
# so we can confidently anticipate the test failure.
if ts_kernel_ver_lt 6 9; then
	TS_KNOWN_FAIL="yes"
fi

ts_init_subtest "single-pid"
if "$TS_CMD_GETINO" 1 &>/dev/null; then
  echo "ok" > "$TS_OUTPUT"
fi
ts_finalize_subtest

ts_init_subtest "multiple-pids"
if "$TS_CMD_GETINO" 1 1 1 1 1 &>/dev/null; then
  echo "ok" > "$TS_OUTPUT"
fi
ts_finalize_subtest

ts_init_subtest "invalid-pid"
if ! "$TS_CMD_GETINO" "invalid-pid" &>/dev/null; then
  echo "ok" > "$TS_OUTPUT"
fi
ts_finalize_subtest

ts_init_subtest "print-pid-option" 
res=$("$TS_CMD_GETINO" --print-pid 1 2>/dev/null | grep -Eo '^[[:digit:]]*:[[:digit:]]*$'); 
if [ -n "$res" ]; then
  echo "ok" > "$TS_OUTPUT"
fi
ts_finalize_subtest

"$TS_CMD_GETINO" --ipcns $$ > /dev/null 2>&1 || ts_skip "namespace ioctl not supported"

ts_init_subtest "ipcns"
if [ -r /proc/self/ns/ipc ]; then
  ts_ipc_ns=$("$TS_CMD_GETINO" --ipcns $$ 2>>"$TS_ERRLOG")
  unshare_ipc_ns=$("$TS_CMD_UNSHARE" --ipc bash -c "$TS_CMD_GETINO --ipcns \$\$" 2>>"$TS_ERRLOG")
  if (( ts_ipc_ns == unshare_ipc_ns )); then
    ts_failed_subtest "IPC namespace unchanged"
  fi
else
  ts_skip_subtest "no IPC namespace support"
fi
ts_finalize_subtest

ts_init_subtest "netns"
if [ -r /proc/self/ns/net ]; then
  ts_net_ns=$("$TS_CMD_GETINO" --netns $$ 2>>"$TS_ERRLOG")
  unshare_net_ns=$("$TS_CMD_UNSHARE" --net bash -c "$TS_CMD_GETINO --netns \$\$" 2>>"$TS_ERRLOG")
  if (( ts_net_ns == unshare_net_ns )); then
    ts_failed_subtest "network namespace unchanged"
  fi
else
  ts_skip_subtest "no network namespace support"
fi
ts_finalize_subtest

ts_init_subtest "mntns"
if [ -r /proc/self/ns/mnt ]; then
  ts_mnt_ns=$("$TS_CMD_GETINO" --mntns $$ 2>>"$TS_ERRLOG")
  unshare_mnt_ns=$("$TS_CMD_UNSHARE" --mount bash -c "$TS_CMD_GETINO --mntns \$\$" 2>>"$TS_ERRLOG")
  if (( ts_mnt_ns == unshare_mnt_ns )); then
    ts_failed_subtest "mount namespace unchanged"
  fi
else
  ts_skip_subtest "no mount namespace support"
fi
ts_finalize_subtest

ts_init_subtest "utsns"
if [ -r /proc/self/ns/uts ]; then
  ts_uts_ns=$("$TS_CMD_GETINO" --utsns $$ 2>>"$TS_ERRLOG")
  unshare_uts_ns=$("$TS_CMD_UNSHARE" --uts bash -c "$TS_CMD_GETINO --utsns \$\$" 2>>"$TS_ERRLOG")
  if (( ts_uts_ns == unshare_uts_ns )); then
    ts_failed_subtest "UTS namespace unchanged"
  fi
else
  ts_skip_subtest "no UTS namespace support"
fi
ts_finalize_subtest

ts_init_subtest "timens"
if [ -r /proc/self/ns/time ]; then
  ts_time_ns=$("$TS_CMD_GETINO" --timens $$ 2>>"$TS_ERRLOG")
  unshare_time_ns=$("$TS_CMD_UNSHARE" --time bash -c "$TS_CMD_GETINO --timens \$\$" 2>>"$TS_ERRLOG")
  if (( ts_time_ns == unshare_time_ns )); then
    ts_failed_subtest "time namespace unchanged"
  fi
else
  ts_skip_subtest "no time namespace support"
fi
ts_finalize_subtest

ts_init_subtest "pidns"
if [ -r /proc/self/ns/pid ]; then
  ts_pid_ns=$("$TS_CMD_GETINO" --pidns $$ 2>>"$TS_ERRLOG")
  unshare_pid_ns=$("$TS_CMD_UNSHARE" --pid --fork bash -c "$TS_CMD_GETINO --pidns \$\$" 2>>"$TS_ERRLOG")
  if (( ts_pid_ns == unshare_pid_ns )); then
    ts_failed_subtest "pid namespace unchanged"
  fi
else
  ts_skip_subtest "no PID namespace support"
fi
ts_finalize_subtest

ts_init_subtest "cgroupns"
if [ -r /proc/self/ns/cgroup ]; then
  ts_cgroup_ns=$("$TS_CMD_GETINO" --cgroupns $$ 2>>"$TS_ERRLOG")
  unshare_cgroup_ns=$("$TS_CMD_UNSHARE" --cgroup bash -c "$TS_CMD_GETINO --cgroupns \$\$" 2>>"$TS_ERRLOG")
  if (( ts_cgroup_ns == unshare_cgroup_ns )); then
    ts_failed_subtest "cgroup namespace unchanged"
  fi
else
  ts_skip_subtest "no cgroup namespace support"
fi
ts_finalize_subtest

ts_init_subtest "userns"
if [ -r /proc/self/ns/user ]; then
  getino_owner="$(stat --format=%U "$TS_CMD_GETINO")"
  ts_user_ns=$("$TS_CMD_GETINO" --userns $$ 2>>"$TS_ERRLOG")
  unshare_user_ns=$("$TS_CMD_RUNUSER" --user "$getino_owner" -- \
                      "$TS_CMD_UNSHARE" --user \
                        bash -c "$TS_CMD_GETINO --userns \$\$" 2>>"$TS_ERRLOG")

  if grep "$("$TS_HELPER_STRERROR" EACCES)" "$TS_ERRLOG" &>/dev/null; then
    ts_skip_subtest "missing permissions to obtain user namespace"
  else
    (( ts_user_ns == unshare_user_ns )) && ts_failed_subtest "user namespace unchanged"
  fi
else
  ts_skip_subtest "no user namespace support"
fi
ts_finalize_subtest


ts_finalize
